#jdbc driver Properties..

spring:
      datasource:
        url: jdbc:oracle:thin:@localhost:1521:orcl
        username: system
        password: manager
        driver-class-name: oracle.jdbc.driver.OracleDriver
        type: com.mchange.v2.c3p0.ComboPooledDataSource
